# Generated by Django 5.2.4 on 2025-10-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='meli_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='کد ملی'),
        ),
        migrations.AddField(
            model_name='user',
            name='uni_code',
            field=models.CharField(blank=True, max_length=24, null=True, unique=True, verbose_name='کد دانشجویی'),
        ),
    ]
