# Generated by Django 5.2.4 on 2025-10-05 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_club'),
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='club.club', verbose_name='انجمن'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_side',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.userside', verbose_name='سمت کاربر'),
        ),
    ]
