# Generated by Django 5.2.7 on 2025-10-10 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='teacher_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='نام استاد'),
        ),
    ]
