# Generated by Django 5.2.4 on 2025-10-05 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=250, verbose_name='موضوع ایمیل')),
                ('to_email', models.EmailField(max_length=254, verbose_name='گیرنده')),
                ('from_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='فرستنده')),
                ('message', models.TextField(verbose_name='متن ایمیل')),
                ('status', models.CharField(choices=[('sent', 'ارسال شد'), ('failed', 'ناموفق'), ('pending', 'در صف')], default='pending', max_length=10, verbose_name='وضعیت ارسال')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='پیام خطا')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ارسال\u200cکننده')),
            ],
            options={
                'verbose_name': 'لاگ ایمیل',
                'verbose_name_plural': 'لاگ ایمیل\u200cها',
                'ordering': ['-date_create'],
            },
        ),
    ]
