# Generated by Django 5.2.4 on 2025-10-05 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان دسته\u200cبندی')),
                ('post_bg_color', models.CharField(blank=True, max_length=7, null=True, verbose_name='رنگ پس\u200cزمینه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی پست',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای پست',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان تگ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
            ],
            options={
                'verbose_name': 'تگ',
                'verbose_name_plural': 'تگ\u200cها',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان مقاله')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='نامک')),
                ('text', models.TextField(blank=True, null=True, verbose_name='متن مقاله')),
                ('post_image', models.ImageField(blank=True, null=True, upload_to='blog_images/', verbose_name='عکس مقاله')),
                ('save_type', models.CharField(choices=[('P', 'منتشر شده'), ('N', 'منتشر نشده')], default='N', max_length=1, verbose_name='وضعیت انتشار')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('post_cat', models.ManyToManyField(to='blog.postcategory', verbose_name='دسته\u200cبندی\u200cها')),
                ('post_tag', models.ManyToManyField(blank=True, to='blog.tag', verbose_name='تگ\u200cها')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'ordering': ['-date_create'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='پیام')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('is_personal', models.BooleanField(default=False, verbose_name='خصوصی')),
                ('is_show', models.BooleanField(default=True, verbose_name='نمایش')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog', verbose_name='مقاله')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.event', verbose_name='رویداد')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.comment', verbose_name='پاسخ به')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کامنت',
                'verbose_name_plural': 'کامنت\u200cها',
                'ordering': ['-date_create'],
            },
        ),
        migrations.CreateModel(
            name='Fav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.blog', verbose_name='مقاله')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.event', verbose_name='رویداد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'علاقه\u200cمندی',
                'verbose_name_plural': 'علاقه\u200cمندی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Save',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.blog', verbose_name='مقاله')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.event', verbose_name='رویداد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'ذخیره',
                'verbose_name_plural': 'ذخیره\u200cها',
            },
        ),
    ]
