# Generated by Django 5.2.4 on 2025-10-05 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='متن مقاله'),
        ),
    ]
