# Generated by Django 5.2.7 on 2025-10-13 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blog_text'),
        ('club', '0002_alter_club_options_alter_club_club_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='club.club', verbose_name='انجمن'),
        ),
    ]
