# Generated by Django 5.2.4 on 2025-10-05 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان دسته\u200cبندی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی رویداد',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای رویداد',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان رویداد')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='نامک')),
                ('teacher_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='نام معلم')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='قیمت')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='ظرفیت')),
                ('access_type', models.CharField(choices=[('web', 'آنلاین'), ('location', 'حضوری')], default='web', max_length=10, verbose_name='نوع دسترسی')),
                ('access_type_address', models.CharField(blank=True, max_length=300, null=True, verbose_name='آدرس/لینک دسترسی')),
                ('event_start_time', models.DateTimeField(blank=True, null=True, verbose_name='شروع رویداد')),
                ('event_end_time', models.DateTimeField(blank=True, null=True, verbose_name='پایان رویداد')),
                ('short_describe', models.CharField(blank=True, max_length=300, null=True, verbose_name='توضیح کوتاه')),
                ('full_describ', models.TextField(blank=True, null=True, verbose_name='توضیح کامل')),
                ('important_info', models.TextField(blank=True, null=True, verbose_name='اطلاعات مهم')),
                ('event_image', models.ImageField(blank=True, null=True, upload_to='event_images/', verbose_name='تصویر رویداد')),
                ('save_type', models.CharField(choices=[('P', 'منتشر شده'), ('N', 'منتشر نشده')], default='N', max_length=1, verbose_name='وضعیت انتشار')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='club.club', verbose_name='کلاب')),
                ('event_cat', models.ManyToManyField(to='event.eventscategory', verbose_name='دسته\u200cبندی\u200cها')),
            ],
            options={
                'verbose_name': 'رویداد',
                'verbose_name_plural': 'رویدادها',
                'ordering': ['-date_create'],
            },
        ),
        migrations.CreateModel(
            name='EventUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.club', verbose_name='کلاب')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event', verbose_name='رویداد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'شرکت\u200cکننده رویداد',
                'verbose_name_plural': 'شرکت\u200cکنندگان رویداد',
            },
        ),
    ]
