# Generated by Django 5.2.4 on 2025-10-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventscategory',
            name='event_bg_color',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='رنگ پس\u200cزمینه'),
        ),
    ]
