# Generated by Django 5.2.4 on 2025-10-05 23:39

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_eventscategory_event_bg_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='full_describ',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='توضیح کامل'),
        ),
        migrations.AlterField(
            model_name='event',
            name='short_describe',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=300, null=True, verbose_name='توضیح کوتاه'),
        ),
    ]
