# Generated by Django 5.2.4 on 2025-10-05 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_event_full_describ_alter_event_short_describe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='full_describ',
            field=models.TextField(blank=True, null=True, verbose_name='توضیح کامل'),
        ),
        migrations.AlterField(
            model_name='event',
            name='short_describe',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='توضیح کوتاه'),
        ),
    ]
