# Generated by Django 5.2.7 on 2025-10-10 00:45

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_event_full_describ_alter_event_short_describe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='full_describ',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='توضیح کامل'),
        ),
        migrations.AlterField(
            model_name='event',
            name='short_describe',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, max_length=300, null=True, verbose_name='توضیح کوتاه'),
        ),
    ]
