# Generated by Django 5.2.7 on 2025-10-13 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_alter_club_options_alter_club_club_color_and_more'),
        ('event', '0006_alter_event_full_describ_alter_event_short_describe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='club.club', verbose_name='انجمن'),
        ),
        migrations.AlterField(
            model_name='event',
            name='teacher_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='نام استاد'),
        ),
    ]
