# Generated by Django 5.2.4 on 2025-10-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان صفحه')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='نامک')),
                ('page_type', models.CharField(choices=[('history', 'تاریخچه'), ('mission', 'ماموریت'), ('team', 'تیم'), ('faq', 'سوالات متداول'), ('other', 'سایر')], default='other', max_length=20, verbose_name='نوع صفحه')),
                ('content', models.TextField(blank=True, null=True, verbose_name='محتوا')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about_pages/', verbose_name='تصویر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'صفحه درباره',
                'verbose_name_plural': 'صفحات درباره',
                'ordering': ['-date_create'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='سوال')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='پاسخ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'سوال متداول',
                'verbose_name_plural': 'سوالات متداول',
                'ordering': ['-date_create'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='نام و نام خانوادگی')),
                ('position', models.CharField(max_length=100, verbose_name='سمت / نقش')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='بیوگرافی')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team_photos/', verbose_name='عکس')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'عضو تیم',
                'verbose_name_plural': 'اعضای تیم',
                'ordering': ['full_name'],
            },
        ),
    ]
