# Generated by Django 5.2.4 on 2025-10-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=150, verbose_name='نام کلاب')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='نامک')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='club_icons/', verbose_name='آیکون')),
                ('club_color', models.CharField(default='#000000', max_length=7, verbose_name='رنگ کلاب')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
            ],
            options={
                'verbose_name': 'کلاب',
                'verbose_name_plural': 'کلاب\u200cها',
                'ordering': ['-date_create'],
            },
        ),
    ]
