# Generated by Django 5.2.7 on 2025-10-10 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'ordering': ['-date_create'], 'verbose_name': 'انجمن ', 'verbose_name_plural': 'انجمن ها'},
        ),
        migrations.AlterField(
            model_name='club',
            name='club_color',
            field=models.CharField(default='#000000', max_length=7, verbose_name='رنگ انجمن'),
        ),
        migrations.AlterField(
            model_name='club',
            name='club_name',
            field=models.CharField(max_length=150, verbose_name='نام انجمن'),
        ),
    ]
